#
# Explicit-Heat-Equation
#
# Required variables:
#  - MAXCOMPILER_SIM_IMAGE: image with MaxCompiler and MaxCompiler Simulator
#  - MAXCOMPILER_DFE_IMAGE: image with MaxCompiler and Quartus II
#

stages:
- make-sim
- make-dfe

make-sim-Explicit-Heat-Equation:
  image: $MAXCOMPILER_SIM_IMAGE
  script:
  - make -C APP/CPUCode RUNRULE='Simulation'
  stage: make-sim
  tags:
  - maxcompiler-sim

make-Coria-Explicit-Heat-Equation:
  image: $MAXCOMPILER_DFE_IMAGE
  script:
  - make -C APP/CPUCode RUNRULE='Coria'
  stage: make-dfe
  tags:
  - maxcompiler-dfe

make-Galava-Explicit-Heat-Equation:
  image: $MAXCOMPILER_DFE_IMAGE
  script:
  - make -C APP/CPUCode RUNRULE='Galava'
  stage: make-dfe
  tags:
  - maxcompiler-dfe

make-Maia-Explicit-Heat-Equation:
  image: $MAXCOMPILER_DFE_IMAGE
  script:
  - make -C APP/CPUCode RUNRULE='Maia'
  stage: make-dfe
  tags:
  - maxcompiler-dfe

make-Isca-Explicit-Heat-Equation:
  image: $MAXCOMPILER_DFE_IMAGE
  script:
  - make -C APP/CPUCode RUNRULE='Isca'
  stage: make-dfe
  tags:
  - maxcompiler-dfe