# --- User's custom definitions
USE_MAXGENFD = 1
USE_SLIC = 1
# ---

MAXCOMPILER_QUOTE   := $(shell printf %q "$(MAXCOMPILERDIR)")

RUNRULE_ARGS        := 
RUNRULE_RUNENV      := LD_LIBRARY_PATH="$(MAXELEROSDIR)/lib:$(LD_LIBRARY_PATH)" 
RUNRULE_MAXFILES    := ExplicitHeatEquation.max  
RUNRULE_MAXFILES_H  := ExplicitHeatEquation.h 
RUNRULE_CFLAGS      := 
RUNRULE_LDFLAGS     := 

TARGET_EXEC         := heat_equation
TARGET_LIBRARY      := 


